default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['JAWSDB_USERNAME'] %>
  password: <%= ENV['JAWSDB_PASSWORD'] %>
  host: <%= ENV['JAWSDB_HOST'] %>
  port: <%= ENV['JAWSDB_PORT'] %>
  database: <%= ENV['JAWSDB_DATABASE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default